export const PALOMPON_BARANGAYS = [
  "Poblacion",
  "Mahawan",
  "Bagong Silang",
  "Cangcosme",
  "Camotes",
  "Mahayahay",
  "Tinugtogan",
  "Baguinbin",
  "Bulak",
  "Bukacon",
  "Bunga",
  "Cangcuasan",
  "Canlambo",
  "Dais",
  "Guadalupe",
  "Hibod-hibod",
  "Hilongos",
  "Ibarra",
  "Jubasan",
  "Libjo",
  "Look",
  "Lucanas",
  "Mancol",
  "Northern Poblacion",
  "Palanog",
  "Panian",
  "San Isidro",
  "San Vicente",
  "Southern Poblacion",
  "Ulakit",
];