export const PALOMPON_BARANGAYS = [
  "Baguinbin",
  "Belen",
  "Bitaog Poblacion (Ypil III)",
  "Buenavista",
  "Caduhaan",
  "Cambakbak",
  "Cambinoy",
  "Cangcosme",
  "Cangmuya",
  "Canipaan",
  "Cantandoy",
  "Cantuhaon",
  "Catigahan",
  "Central 1 (Poblacion)",
  "Central 2 (Poblacion)",
  "Cruz",
  "Duljugan",
  "Guiwan 1 (Poblacion)",
  "Guiwan 2 (Poblacion)",
  "Himarco",
  "Hinablayan Poblacion (Central 3)",
  "Hinagbuan",
  "Lat-osan",
  "Liberty",
  "Lomonon",
  "Mabini",
  "Magsaysay",
  "Masaba",
  "Mazawalo Poblacion (Lili-on)",
  "Parilla",
  "Pinagdait Poblacion (Ypil I)",
  "Pinaghi-usa Poblacion (Ypil II)",
  "Plaridel",
  "Rizal",
  "Sabang",
  "San Guillermo",
  "San Isidro",
  "San Joaquin",
  "San Juan",
  "San Miguel",
  "San Pablo",
  "San Pedro",
  "San Roque",
  "Santiago",
  "Taberna",
  "Tabunok",
  "Tambis",
  "Tinabilan",
  "Tinago",
  "Tinubdan",
];